name: build-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.ACTION_TOKEN }}
    
    - name: Install graphviz-dev
      run: sudo apt-get install -y graphviz-dev
      
    - name: Build
      run: cargo build --verbose
      
  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.ACTION_TOKEN }}
    
    - name: Install graphviz
      run: brew install graphviz
      
    - name: Build
      run: cargo build --verbose
