name: build-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with: 
         submodules: recursive
    - name: Install graphviz-dev
      run: sudo apt-get install -y graphviz-dev
    - name: Build
      run: cargo build --verbose
