name: build-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Add SSH private keys for submodules
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - run: git submodule update --init --recursive
    
    - name: Install graphviz-dev
      run: sudo apt-get install -y graphviz-dev
      
    - name: Build
      run: cargo build --verbose
